//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var controllerId = 'albumEditCtrl';
    angular.module('app').controller(controllerId, ['common',  'artistDataService', albumEdit]);

    function albumEdit(common,  artistDataService) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);

        var vm = this;
        vm.artists = [];
        vm.title = 'AlbumEdit';
       

        activate();

        function activate() {
            var promises = [getArtists()];
            common.activateController(promises, controllerId)
                .then(function () { log('Activated Album Edit View'); });
        }
        
        
        function getArtists() {
            return artistDataService.getData().then(function (results) {
                return vm.artists = results.data;
            });
        }

      
    }
})();

