//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var controllerId = 'albumIndexCtrl';
    angular.module('app').controller(controllerId, ['common', 'albumDataService', albumList]);

    function albumList(common, albumDataService) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);

        var vm = this;
        vm.news = {
            title: 'Album List',
            description: 'Album List'
        };
       
        vm.pagableResults = [];
        vm.title = 'AlbumList';
        vm.sortExpression = 'AlbumId';
        vm.currentPage = 1;
        vm.pageSize = 10;
        vm.deleteAlbum = deleteAlbum;

        activate();

        vm.pageChanged = function () {
            return getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize);
        };

        function activate() {
            var promises = [getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize)];
            common.activateController(promises, controllerId)
                .then(function () { log('Activated Album List View'); });
        }
        
        function getDataPageable(sortExpression, page, pageSize) {
            return albumDataService.getDataPageable(sortExpression, page, pageSize).then(function (results) {
                return  vm.pagableResults = results.data;
              });
        }

        function deleteAlbum(albumId) {
            alert("test worked");
          //  return albumDataService.deleteAlbum(albumId);
        };
    }
})();

