//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var controllerId = 'employeeIndexCtrl';
    angular.module('app').controller(controllerId, ['common', 'employeeDataService', employeeList]);

    function employeeList(common, employeeDataService) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);

        var vm = this;
        vm.news = {
            title: 'Employee List',
            description: 'Employee List'
        };
       
        vm.pagableResults = [];
        vm.title = 'EmployeeList';
        vm.sortExpression = 'EmployeeId';
        vm.currentPage = 1;
        vm.pageSize = 10;
        vm.deleteEmployee = deleteEmployee;

        activate();

        vm.pageChanged = function () {
            return getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize);
        };

        function activate() {
            var promises = [getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize)];
            common.activateController(promises, controllerId)
                .then(function () { log('Activated Employee List View'); });
        }
        
        function getDataPageable(sortExpression, page, pageSize) {
            return employeeDataService.getDataPageable(sortExpression, page, pageSize).then(function (results) {
                return  vm.pagableResults = results.data;
              });
        }

        function deleteEmployee(employeeId) {
            alert("test worked");
          //  return employeeDataService.deleteEmployee(employeeId);
        };
    }
})();

