'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities

  
 Namespace Chinook.Data.Repository     
    Public Interface IGenreRepository
        Function GetData()  as ICollection(Of Genre)
        Sub Update( ByVal genreId As Int32,  ByVal name As String) 
        Sub Update(ByVal genre as Genre) 
        Function Insert( ByVal genreId As Int32,  ByVal name As String)  as Int32
        Function Insert(ByVal genre as Genre)  as Int32
        Sub Delete( ByVal genreId As Int32) 
        Sub Delete(ByVal genre as Genre) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Genre)
        Function GetRowCount()  as Int32
        Function GetDataByGenreId( ByVal genreId As Int32)  as ICollection(Of Genre)
    End Interface 
End NameSpace
  