'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities


Namespace Chinook.Data.Repository
    Public Interface IGenreRepository
        Function GetData() As ICollection(Of Genre)
        Sub Update(ByVal genreId As Int32, ByVal name As String)
        Sub Update(ByVal genre As Genre)
        Function Insert(ByVal genreId As Int32, ByVal name As String) As Int32
        Function Insert(ByVal genre As Genre) As Int32
        Sub Delete(ByVal genreId As Int32)
        Sub Delete(ByVal genre As Genre)
        Function GetPagableSubSet(ByVal sortExpression As String, ByVal startRowIndex As Int32, ByVal maximumRows As Int32) As ICollection(Of Genre)
        Function GetRowCount() As Int32
        Function GetDataByGenreId(ByVal genreId As Int32) As ICollection(Of Genre)
    End Interface
End Namespace
