'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities


Namespace Chinook.Data.Repository
    Public Interface IInvoiceRepository
        Function GetData() As ICollection(Of Invoice)
        Sub Update(ByVal invoiceId As Int32, ByVal customerId As Int32, ByVal invoiceDate As DateTime, ByVal billingAddress As String, ByVal billingCity As String, ByVal billingState As String, ByVal billingCountry As String, ByVal billingPostalCode As String, ByVal total As Decimal)
        Sub Update(ByVal invoice As Invoice)
        Function Insert(ByVal invoiceId As Int32, ByVal customerId As Int32, ByVal invoiceDate As DateTime, ByVal billingAddress As String, ByVal billingCity As String, ByVal billingState As String, ByVal billingCountry As String, ByVal billingPostalCode As String, ByVal total As Decimal) As Int32
        Function Insert(ByVal invoice As Invoice) As Int32
        Sub Delete(ByVal invoiceId As Int32)
        Sub Delete(ByVal invoice As Invoice)
        Function GetPageable(ByVal sortExpression As String, ByVal startRowIndex As Int32, ByVal pageSize As Int32) As ICollection(Of Invoice)
        Function GetRowCount() As Int32
        Function GetDataByInvoiceId(ByVal invoiceId As Int32) As ICollection(Of Invoice)
        Function GetDataByCustomerId(ByVal customerId As Int32) As ICollection(Of Invoice)
        Function GetDataByCustomerIdPageable(ByVal sortExpression As String, ByVal startRowIndex As Int32, ByVal pageSize As Int32, ByVal customerId As Int32) As ICollection(Of Invoice)
        Function GetDataByCustomerIdRowCount(ByVal customerId As Int32) As Int32
    End Interface
End Namespace
