'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities

  
 Namespace Chinook.Data.Repository     
    Public Interface IMediaTypeRepository
        Function GetData()  as ICollection(Of MediaType)
        Sub Update( ByVal mediaTypeId As Int32,  ByVal name As String) 
        Sub Update(ByVal mediaType as MediaType) 
        Function Insert( ByVal mediaTypeId As Int32,  ByVal name As String)  as Int32
        Function Insert(ByVal mediaType as MediaType)  as Int32
        Sub Delete( ByVal mediaTypeId As Int32) 
        Sub Delete(ByVal mediaType as MediaType) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of MediaType)
        Function GetRowCount()  as Int32
        Function GetDataByMediaTypeId( ByVal mediaTypeId As Int32)  as ICollection(Of MediaType)
    End Interface 
End NameSpace
  