'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities

  
 Namespace Chinook.Data.Repository     
    Public Interface IPlaylistTrackRepository
        Function GetData()  as ICollection(Of PlaylistTrack)
        Sub Update( ByVal playlistId As Int32,  ByVal trackId As Int32) 
        Sub Update(ByVal playlistTrack as PlaylistTrack) 
        Function Insert( ByVal playlistId As Int32,  ByVal trackId As Int32)  as ICollection(Of PlaylistTrack)
        Function Insert(ByVal playlistTrack as PlaylistTrack)  as ICollection(Of PlaylistTrack)
        Sub Delete( ByVal playlistId As Int32,  ByVal trackId As Int32) 
        Sub Delete(ByVal playlistTrack as PlaylistTrack) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of PlaylistTrack)
        Function GetRowCount()  as Int32
        Function GetDataByPlaylistIdTrackId( ByVal playlistId As Int32,  ByVal trackId As Int32)  as ICollection(Of PlaylistTrack)
        Function GetDataByPlaylistId( ByVal playlistId As Int32)  as ICollection(Of PlaylistTrack)
        Function GetDataByPlaylistIdPageable( ByVal playlistId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of PlaylistTrack)
        Function GetDataByPlaylistIdRowCount( ByVal playlistId As Int32)  as Int32
        Function GetDataByTrackId( ByVal trackId As Int32)  as ICollection(Of PlaylistTrack)
        Function GetDataByTrackIdPageable( ByVal trackId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of PlaylistTrack)
        Function GetDataByTrackIdRowCount( ByVal trackId As Int32)  as Int32
    End Interface 
End NameSpace
  