'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities


Namespace Chinook.Data.Repository
    Public Interface IPlaylistTrackRepository
        Function GetData() As ICollection(Of PlaylistTrack)
        Sub Update(ByVal playlistId As Int32, ByVal trackId As Int32)
        Sub Update(ByVal playlistTrack As PlaylistTrack)
        Function Insert(ByVal playlistId As Int32, ByVal trackId As Int32) As ICollection(Of PlaylistTrack)
        Function Insert(ByVal playlistTrack As PlaylistTrack) As ICollection(Of PlaylistTrack)
        Sub Delete(ByVal playlistId As Int32, ByVal trackId As Int32)
        Sub Delete(ByVal playlistTrack As PlaylistTrack)
        Function GetPagableSubSet(ByVal sortExpression As String, ByVal startRowIndex As Int32, ByVal maximumRows As Int32) As ICollection(Of PlaylistTrack)
        Function GetRowCount() As Int32
        Function GetDataByPlaylistIdTrackId(ByVal playlistId As Int32, ByVal trackId As Int32) As ICollection(Of PlaylistTrack)
        Function GetDataByPlaylistId(ByVal playlistId As Int32) As ICollection(Of PlaylistTrack)
        Function GetDataByPlaylistIdPagableSubSet(ByVal sortExpression As String, ByVal startRowIndex As Int32, ByVal maximumRows As Int32, ByVal playlistId As Int32) As ICollection(Of PlaylistTrack)
        Function GetDataByPlaylistIdRowCount(ByVal playlistId As Int32) As Int32
        Function GetDataByTrackId(ByVal trackId As Int32) As ICollection(Of PlaylistTrack)
        Function GetDataByTrackIdPagableSubSet(ByVal sortExpression As String, ByVal startRowIndex As Int32, ByVal maximumRows As Int32, ByVal trackId As Int32) As ICollection(Of PlaylistTrack)
        Function GetDataByTrackIdRowCount(ByVal trackId As Int32) As Int32
    End Interface
End Namespace
