'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities

  
 Namespace Chinook.Data.Repository     
    Public Interface ITrackRepository
        Function GetData()  as ICollection(Of Track)
        Sub Update( ByVal trackId As Int32,  ByVal name As String,  ByVal albumId As  Nullable(Of Int32) ,  ByVal mediaTypeId As Int32,  ByVal genreId As  Nullable(Of Int32) ,  ByVal composer As String,  ByVal milliseconds As Int32,  ByVal bytes As  Nullable(Of Int32) ,  ByVal unitPrice As Decimal) 
        Sub Update(ByVal track as Track) 
        Function Insert( ByVal trackId As Int32,  ByVal name As String,  ByVal albumId As  Nullable(Of Int32) ,  ByVal mediaTypeId As Int32,  ByVal genreId As  Nullable(Of Int32) ,  ByVal composer As String,  ByVal milliseconds As Int32,  ByVal bytes As  Nullable(Of Int32) ,  ByVal unitPrice As Decimal)  as Int32
        Function Insert(ByVal track as Track)  as Int32
        Sub Delete( ByVal trackId As Int32) 
        Sub Delete(ByVal track as Track) 
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Track)
        Function GetRowCount()  as Int32
        Function GetDataByTrackId( ByVal trackId As Int32)  as ICollection(Of Track)
        Function GetTracksByPlaylistId( ByVal playlistId As Int32)  as ICollection(Of Track)
        Function GetTracksByPlaylistIdPageable( ByVal playlistId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Track)
        Function GetTracksByPlaylistIdRowCount( ByVal playlistId As Int32)  as Int32
        Function GetDataByAlbumId( ByVal albumId As Int32)  as ICollection(Of Track)
        Function GetDataByAlbumIdPageable( ByVal albumId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Track)
        Function GetDataByAlbumIdRowCount( ByVal albumId As Int32)  as Int32
        Function GetDataByGenreId( ByVal genreId As Int32)  as ICollection(Of Track)
        Function GetDataByGenreIdPageable( ByVal genreId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Track)
        Function GetDataByGenreIdRowCount( ByVal genreId As Int32)  as Int32
        Function GetDataByMediaTypeId( ByVal mediaTypeId As Int32)  as ICollection(Of Track)
        Function GetDataByMediaTypeIdPageable( ByVal mediaTypeId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as ICollection(Of Track)
        Function GetDataByMediaTypeIdRowCount( ByVal mediaTypeId As Int32)  as Int32
    End Interface 
End NameSpace
  