'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Collections.Generic
Imports Chinook.Data
Imports Chinook.Domain.Entities
Imports Chinook.Data.DbCommandProvider
Imports System.Collections.ObjectModel
  
Namespace Chinook.Data.Repository    
    
    <Global.System.ComponentModel.DataObjectAttribute(true)>  _
    Public Class DbPlaylistRepository
        Implements IPlaylistRepository
        Implements IDisposable

        Private ReadOnly _dbPlaylistCommandProvider As IDbPlaylistCommandProvider
        Private _dbConnHolder As DbConnectionHolder = Nothing

        Public Sub New(ByVal dbPlaylistCommandProvider As IDbPlaylistCommandProvider)
            _dbPlaylistCommandProvider = dbPlaylistCommandProvider
            _dbConnHolder =_dbPlaylistCommandProvider.PlaylistDbConnectionHolder
        End Sub

      
    ''' <summary>
    ''' Selects one or more records from the Playlist table 
    ''' </summary>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)> _ 
    Public Function GetData()  as ICollection(Of Playlist) Implements IPlaylistRepository.GetData
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetDataDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Playlist)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Playlist( reader.GetInt32("PlaylistId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Updates one or more records from the Playlist table 
    ''' </summary>
   ''' <param name="PlaylistId"></param>
   ''' <param name="Name"></param>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, true)> _ 
    Public Sub Update( ByVal playlistId As Int32,  ByVal name As String)  Implements IPlaylistRepository.Update
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetUpdateDbCommand(PlaylistId, Name)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
          Command.ExecuteNonQuery
            _dbConnHolder.Close()
    End Sub
  
    ''' <summary>
    ''' Updates one or more records from the Playlist table 
    ''' </summary>
    ''' <param name="Playlist"></param>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Update, False)> _ 
    Public Sub Update(ByVal playlist as Playlist)  Implements IPlaylistRepository.Update
             With Playlist
Update(.PlaylistId, .Name)
       End With

    End Sub
  
    ''' <summary>
    ''' Inserts an entity of Playlist into the database.
    ''' </summary>
   ''' <param name="PlaylistId"></param>
   ''' <param name="Name"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, true)> _ 
    Public Function Insert( ByVal playlistId As Int32,  ByVal name As String)  as Int32 Implements IPlaylistRepository.Insert
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetInsertDbCommand(PlaylistId, Name)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Int32  = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
  
    ''' <summary>
    ''' Inserts an entity of Playlist into the database.
    ''' </summary>
    ''' <param name="Playlist"></param>
    ''' <returns></returns>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Insert, False)> _ 
    Public Function Insert(ByVal playlist as Playlist)  as Int32 Implements IPlaylistRepository.Insert
             With Playlist
 Return Insert(.PlaylistId, .Name)
       End With

    End Function
  
    ''' <summary>
    ''' Deletes one or more records from the Playlist table 
    ''' </summary>
   ''' <param name="PlaylistId"></param>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, true)> _ 
    Public Sub Delete( ByVal playlistId As Int32)  Implements IPlaylistRepository.Delete
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetDeleteDbCommand(PlaylistId)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
          Command.ExecuteNonQuery
            _dbConnHolder.Close()
    End Sub
  
    ''' <summary>
    ''' Deletes one or more records from the Playlist table 
    ''' </summary>
    ''' <param name="Playlist"></param>
    ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Delete, False)> _ 
    Public Sub Delete(ByVal playlist as Playlist)  Implements IPlaylistRepository.Delete
             With Playlist
Delete(.PlaylistId)
       End With

    End Sub
  
    ''' <summary>
    ''' Function GetPagableSubSet returns a IDataReader populated with a subset of data from Playlist
    ''' </summary>
   ''' <param name="sortExpression"></param>
   ''' <param name="startRowIndex"></param>
   ''' <param name="MaximumRows"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetPagableSubSet( ByVal sortExpression As String,  ByVal startRowIndex As Int32,  ByVal maximumRows As Int32)  as ICollection(Of Playlist) Implements IPlaylistRepository.GetPagableSubSet
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetPagableSubSetDbCommand(sortExpression, startRowIndex, MaximumRows)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Playlist)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Playlist( reader.GetInt32("PlaylistId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetRowCount returns the row count for Playlist
    ''' </summary>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetRowCount()  as Int32 Implements IPlaylistRepository.GetRowCount
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetRowCountDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Int32  = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
  
    ''' <summary>
    ''' Function GetDataByPlaylistId returns a IDataReader for Playlist
    ''' </summary>
   ''' <param name="PlaylistId"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetDataByPlaylistId( ByVal playlistId As Int32)  as ICollection(Of Playlist) Implements IPlaylistRepository.GetDataByPlaylistId
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetDataByPlaylistIdDbCommand(PlaylistId)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Playlist)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Playlist( reader.GetInt32("PlaylistId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetPlaylistsByTrackId returns a Track
    ''' </summary>
   ''' <param name="TrackId"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetPlaylistsByTrackId( ByVal trackId As Int32)  as ICollection(Of Playlist) Implements IPlaylistRepository.GetPlaylistsByTrackId
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetPlaylistsByTrackIdDbCommand(TrackId)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Playlist)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Playlist( reader.GetInt32("PlaylistId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetPlaylistsByTrackId returns a Track
    ''' </summary>
   ''' <param name="TrackId"></param>
   ''' <param name="sortExpression"></param>
   ''' <param name="startRowIndex"></param>
   ''' <param name="MaximumRows"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetPlaylistsByTrackIdPagableSubSet( ByVal trackId As Int32,  ByVal sortExpression As String,  ByVal startRowIndex As Int32,  ByVal maximumRows As Int32)  as ICollection(Of Playlist) Implements IPlaylistRepository.GetPlaylistsByTrackIdPagableSubSet
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetPlaylistsByTrackIdPagableSubSetDbCommand(TrackId, sortExpression, startRowIndex, MaximumRows)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim entList as new Collection(Of Playlist)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                 Dim tempEntity As New Playlist( reader.GetInt32("PlaylistId"),  reader.GetString("Name") )
                 entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
    
    End Function
  
    ''' <summary>
    ''' Function GetPlaylistsByTrackIdRowCount returns the row count for Playlist
    ''' </summary>
   ''' <param name="TrackId"></param>''' <returns></returns>
   ''' <remarks></remarks> 
  <Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], false)> _ 
    Public Function GetPlaylistsByTrackIdRowCount( ByVal trackId As Int32)  as Int32 Implements IPlaylistRepository.GetPlaylistsByTrackIdRowCount
        Dim command As IDbCommand = _dbPlaylistCommandProvider.GetGetPlaylistsByTrackIdRowCountDbCommand(TrackId)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
              Dim returnValue As Int32  = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue 

    End Function
   
  
#Region "IDisposable Support"
        Private disposedValue As Boolean
        Protected Overridable Sub Dispose(disposing As Boolean)
            If Not Me.disposedValue Then
                If disposing Then
                    Select Case _dbConnHolder.Connection.State
                        Case ConnectionState.Open
                            _dbConnHolder.Close()
                    End Select
                    _dbConnHolder = Nothing
                End If

            End If
            Me.disposedValue = True
        End Sub

        Public Sub Dispose() Implements IDisposable.Dispose
            Dispose(True)
            GC.SuppressFinalize(Me)
        End Sub
#End Region
 
  End Class 
End NameSpace
