'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data

Namespace Chinook.Data.DbCommandProvider
    Public Interface IDbPlaylistCommandProvider
        ReadOnly Property PlaylistDbConnectionHolder() As DbConnectionHolder
        ReadOnly Property DbConnectionName As String
        Function GetGetDataDbCommand() As IDbCommand
        Function GetUpdateDbCommand( ByVal playlistId As Int32,  ByVal name As String) As IDbCommand
        Function GetInsertDbCommand( ByVal playlistId As Int32,  ByVal name As String) As IDbCommand
        Function GetDeleteDbCommand( ByVal playlistId As Int32) As IDbCommand
        Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetRowCountDbCommand() As IDbCommand
        Function GetGetDataByPlaylistIdDbCommand( ByVal playlistId As Int32) As IDbCommand
        Function GetGetPlaylistsByTrackIdDbCommand( ByVal trackId As Int32) As IDbCommand
        Function GetGetPlaylistsByTrackIdPageableDbCommand( ByVal trackId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetPlaylistsByTrackIdRowCountDbCommand( ByVal trackId As Int32) As IDbCommand

    End Interface
End Namespace
