//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Chinook.Data.DbCommandProvider;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers.Api
{
    public class InvoiceLineApiController : ApiController
    {
        private readonly IInvoiceLineRepository _dbRepository;

        public InvoiceLineApiController(IDbInvoiceLineCommandProvider dbCommandProvider)
        {
            _dbRepository = new DbInvoiceLineRepository(dbCommandProvider);
        }

        [HttpGet]
        public IQueryable<InvoiceLine> GetData()
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [HttpPut]
        public void Update(Int32 invoiceLineId, Int32 invoiceId, Int32 trackId, Decimal unitPrice, Int32 quantity)
        {
            _dbRepository.Update(invoiceLineId, invoiceId, trackId, unitPrice, quantity);
        }


        [HttpPut]
        public void Update(InvoiceLine invoiceLine)
        {
            Update((Int32)invoiceLine.InvoiceLineId, (Int32)invoiceLine.InvoiceId, (Int32)invoiceLine.TrackId, (decimal)invoiceLine.UnitPrice, (Int32)invoiceLine.Quantity);
        }

        [HttpPost]
        public Int32 Insert(Int32 invoiceLineId, Int32 invoiceId, Int32 trackId, Decimal unitPrice, Int32 quantity)
        {
            return _dbRepository.Insert(invoiceLineId, invoiceId, trackId, unitPrice, quantity);
        }


        [HttpPost]
        public Int32 Insert(InvoiceLine invoiceLine)
        {
            return Insert((Int32)invoiceLine.InvoiceLineId, (Int32)invoiceLine.InvoiceId, (Int32)invoiceLine.TrackId, (decimal)invoiceLine.UnitPrice, (Int32)invoiceLine.Quantity);
        }

        [HttpDelete]
        public void Delete(Int32 invoiceLineId)
        {
            _dbRepository.Delete(invoiceLineId);
        }


        [HttpDelete]
        public void Delete(InvoiceLine invoiceLine)
        {
            Delete((Int32)invoiceLine.InvoiceLineId);
        }

        [HttpGet]
        public HttpResponseMessage GetDataPageable(String sortExpression, Int32 page, Int32 pageSize) 
        {
              if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataPageable(sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetRowCount();
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "GetDataPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [HttpGet]
        public IQueryable<InvoiceLine> GetDataByInvoiceLineId(Int32 invoiceLineId)
        {
            return _dbRepository.GetDataByInvoiceLineId(invoiceLineId).AsQueryable();
        }

        [Route("api/invoices/{invoiceId}/invoiceLines/all", Name = "GetinvoiceLinesByInvoiceIdRoute")]
        [HttpGet]
        public IQueryable<InvoiceLine> GetDataByInvoiceId(Int32 invoiceId)
        {
            return _dbRepository.GetDataByInvoiceId(invoiceId).AsQueryable();
        }

        [Route("api/invoices/{invoiceId}/invoiceLines", Name = "GetinvoiceLinesByInvoiceIdPageableRoute")]
        [HttpGet]
        public HttpResponseMessage GetDataByInvoiceIdPageable(Int32 invoiceId, String sortExpression, Int32 page, Int32 pageSize)
        {
            if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results = _dbRepository.GetDataByInvoiceIdPageable(invoiceId, sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetDataByInvoiceIdRowCount(invoiceId);
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "GetDataByInvoiceIdPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [Route("api/invoiceLines/{trackId}/all", Name = "GetinvoiceLinesByTrackIdRoute")]
        [HttpGet]
        public IQueryable<InvoiceLine> GetDataByTrackId(Int32 trackId)
        {
            return _dbRepository.GetDataByTrackId(trackId).AsQueryable();
        }

        [Route("api/invoiceLines/{trackId}", Name = "GetinvoiceLinesByTrackIdPageableRoute")]
        [HttpGet]
        public HttpResponseMessage GetDataByTrackIdPageable(Int32 trackId, String sortExpression, Int32 page, Int32 pageSize)
        {
            if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results = _dbRepository.GetDataByTrackIdPageable(trackId, sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetDataByTrackIdRowCount(trackId);
            var pagedResults = PagedResultHelper.CreatePagedResult(Request, "GetDataByTrackIdPageableRoute", page,
                pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }


    }
}
