//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumRepository _dbAlbumRepository;
        private readonly IArtistRepository _dbArtistRepository;
        

        public AlbumController(IAlbumRepository dbAlbumRepository, IArtistRepository dbArtistRepository)
        {
            _dbAlbumRepository = dbAlbumRepository;
            _dbArtistRepository = dbArtistRepository; 
            
        }
        
        // GET: Album
        public ActionResult Index()
        {
            return View();
        }

        // GET: Album/Details/5
        [Route("Album/Details/{albumId}", Name = "GetAlbumDetails")]
        public ActionResult Details(Int32 albumId)
        {
            return View(_dbAlbumRepository.GetDataByAlbumId(albumId).FirstOrDefault());
        }

        // GET: Album/Create
        public ActionResult Create()
        {
            ViewBag.Artists = new SelectList(_dbArtistRepository.GetData(), "ArtistId", "ArtistId");
            
            return View();
        }

        // POST: Album/Create
        [HttpPost]
        public ActionResult Create(Album album)
        {
            try
            {
                _dbAlbumRepository.Insert(album);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(album);
            }
        }

        // GET: Album/Edit/5
        [Route("Album/Edit/{albumId}", Name = "GetAlbumEdit")]
        public ActionResult Edit(Int32 albumId)
        {
        	var album = _dbAlbumRepository.GetDataByAlbumId(albumId).FirstOrDefault();    
            if (album != null) ViewBag.Artists = new SelectList(_dbArtistRepository.GetData(), "ArtistId", "Name", album.ArtistId);
            
            return View(album);
        }

        // POST: Album/Edit/5
        [Route("Album/Edit/{albumId}", Name = "PostAlbumEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 albumId, Album album)
        {
            try
            {
                _dbAlbumRepository.Update(album);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(album);
            }
        }
   }
}
