//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _dbCustomerRepository;
        private readonly IEmployeeRepository _dbEmployeeRepository;
        

        public CustomerController(ICustomerRepository dbCustomerRepository, IEmployeeRepository dbEmployeeRepository)
        {
            _dbCustomerRepository = dbCustomerRepository;
            _dbEmployeeRepository = dbEmployeeRepository; 
            
        }
        
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        // GET: Customer/Details/5
        [Route("Customer/Details/{customerId}", Name = "GetCustomerDetails")]
        public ActionResult Details(Int32 customerId)
        {
            return View(_dbCustomerRepository.GetDataByCustomerId(customerId).FirstOrDefault());
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            ViewBag.Employees = new SelectList(_dbEmployeeRepository.GetData(), "EmployeeId", "EmployeeId");
            
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            try
            {
                _dbCustomerRepository.Insert(customer);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(customer);
            }
        }

        // GET: Customer/Edit/5
        [Route("Customer/Edit/{customerId}", Name = "GetCustomerEdit")]
        public ActionResult Edit(Int32 customerId)
        {
        	var customer = _dbCustomerRepository.GetDataByCustomerId(customerId).FirstOrDefault();    
            if (customer != null) ViewBag.Employees = new SelectList(_dbEmployeeRepository.GetData(), "EmployeeId", "EmployeeId", customer.SupportRepId);
            
            return View(customer);
        }

        // POST: Customer/Edit/5
        [Route("Customer/Edit/{customerId}", Name = "PostCustomerEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 customerId, Customer customer)
        {
            try
            {
                _dbCustomerRepository.Update(customer);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(customer);
            }
        }
   }
}
