//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.UI.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _dbEmployeeRepository;
        

        public EmployeeController(IEmployeeRepository dbEmployeeRepository)
        {
            _dbEmployeeRepository = dbEmployeeRepository;
            
        }
        
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employee/Details/5
        [Route("Employee/Details/{employeeId}", Name = "GetEmployeeDetails")]
        public ActionResult Details(Int32 employeeId)
        {
            return View(_dbEmployeeRepository.GetDataByEmployeeId(employeeId).FirstOrDefault());
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            ViewBag.Employees = new SelectList(_dbEmployeeRepository.GetData(), "EmployeeId", "EmployeeId");
            
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            try
            {
                _dbEmployeeRepository.Insert(employee);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(employee);
            }
        }

        // GET: Employee/Edit/5
        [Route("Employee/Edit/{employeeId}", Name = "GetEmployeeEdit")]
        public ActionResult Edit(Int32 employeeId)
        {
        	var employee = _dbEmployeeRepository.GetDataByEmployeeId(employeeId).FirstOrDefault();    
            if (employee != null) ViewBag.Employees = new SelectList(_dbEmployeeRepository.GetData(), "EmployeeId", "EmployeeId", employee.ReportsTo);
            
            return View(employee);
        }

        // POST: Employee/Edit/5
        [Route("Employee/Edit/{employeeId}", Name = "PostEmployeeEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 employeeId, Employee employee)
        {
            try
            {
                _dbEmployeeRepository.Update(employee);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(employee);
            }
        }
   }
}
