//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _dbRepository;

        public EmployeeController(IEmployeeRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
        
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employee/Details/5
        [Route("Employee/Details/{employeeId}", Name = "GetEmployeeDetails")]
        public ActionResult Details(Int32 employeeId)
        {
            return View(_dbRepository.GetDataByEmployeeId(employeeId).FirstOrDefault());
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            try
            {
                _dbRepository.Insert(employee);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(employee);
            }
        }

        // GET: Employee/Edit/5
        [Route("Employee/Edit/{employeeId}", Name = "GetEmployeeEdit")]
        public ActionResult Edit(Int32 employeeId)
        {
            return View(_dbRepository.GetDataByEmployeeId(employeeId).FirstOrDefault());
        }

        // POST: Employee/Edit
        [Route("Employee/Edit", Name = "PostEmployeeEdit")]
        [HttpPost]
        public ActionResult Edit(Employee employee)
        {
            try
            {
                _dbRepository.Update(employee);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(employee);
            }
        }
   }
}
