//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly IInvoiceRepository _dbRepository;

        public InvoiceController(IInvoiceRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
        
        // GET: Invoice
        public ActionResult Index()
        {
            return View();
        }

        // GET: Invoice/Details/5
        [Route("Invoice/Details/{invoiceId}", Name = "GetInvoiceDetails")]
        public ActionResult Details(Int32 invoiceId)
        {
            return View(_dbRepository.GetDataByInvoiceId(invoiceId).FirstOrDefault());
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Invoice/Create
        [HttpPost]
        public ActionResult Create(Invoice invoice)
        {
            try
            {
                _dbRepository.Insert(invoice);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(invoice);
            }
        }

        // GET: Invoice/Edit/5
        [Route("Invoice/Edit/{invoiceId}", Name = "GetInvoiceEdit")]
        public ActionResult Edit(Int32 invoiceId)
        {
            return View(_dbRepository.GetDataByInvoiceId(invoiceId).FirstOrDefault());
        }

        // POST: Invoice/Edit
        [Route("Invoice/Edit", Name = "PostInvoiceEdit")]
        [HttpPost]
        public ActionResult Edit(Invoice invoice)
        {
            try
            {
                _dbRepository.Update(invoice);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(invoice);
            }
        }
   }
}
