//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class InvoiceLineController : Controller
    {
        private readonly IInvoiceLineRepository _dbRepository;

        public InvoiceLineController(IInvoiceLineRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
        
        // GET: InvoiceLine
        public ActionResult Index()
        {
            return View();
        }

        // GET: InvoiceLine/Details/5
        public ActionResult Details(Int32 invoiceLineId)
        {
            return View(_dbRepository.GetDataByInvoiceLineId(invoiceLineId).FirstOrDefault());
        }

        // GET: InvoiceLine/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InvoiceLine/Create
        [HttpPost]
        public ActionResult Create(InvoiceLine invoiceLine)
        {
            try
            {
                _dbRepository.Insert(invoiceLine);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(invoiceLine);
            }
        }

       public ActionResult Edit(Int32 id)
        {
            return View(_dbRepository.GetDataByInvoiceLineId(id).FirstOrDefault());
        }

        // POST: InvoiceLine/Edit/5
        [HttpPost]
        public ActionResult Edit(InvoiceLine invoiceLine)
        {
            try
            {
                _dbRepository.Update(invoiceLine);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(invoiceLine);
            }
        }
   
       
    }
}
