//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class MediaTypeController : Controller
    {
        private readonly IMediaTypeRepository _dbRepository;

        public MediaTypeController(IMediaTypeRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
        
        // GET: MediaType
        public ActionResult Index()
        {
            return View();
        }

        // GET: MediaType/Details/5
        [Route("MediaType/Details/{mediaTypeId}", Name = "GetMediaTypeDetails")]
        public ActionResult Details(Int32 mediaTypeId)
        {
            return View(_dbRepository.GetDataByMediaTypeId(mediaTypeId).FirstOrDefault());
        }

        // GET: MediaType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MediaType/Create
        [HttpPost]
        public ActionResult Create(MediaType mediaType)
        {
            try
            {
                _dbRepository.Insert(mediaType);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(mediaType);
            }
        }

        // GET: MediaType/Edit/5
        [Route("MediaType/Edit/{mediaTypeId}", Name = "GetMediaTypeEdit")]
        public ActionResult Edit(Int32 mediaTypeId)
        {
            return View(_dbRepository.GetDataByMediaTypeId(mediaTypeId).FirstOrDefault());
        }

        // POST: MediaType/Edit
        [Route("MediaType/Edit", Name = "PostMediaTypeEdit")]
        [HttpPost]
        public ActionResult Edit(MediaType mediaType)
        {
            try
            {
                _dbRepository.Update(mediaType);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(mediaType);
            }
        }
   }
}
