//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class PlaylistTrackController : Controller
    {
        private readonly IPlaylistTrackRepository _dbRepository;

        public PlaylistTrackController(IPlaylistTrackRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
        
        // GET: PlaylistTrack
        public ActionResult Index()
        {
            return View();
        }

        // GET: PlaylistTrack/Details/5
        public ActionResult Details(Int32 PlaylistId, Int32 TrackId)
        {
            return View(_dbRepository.GetDataByPlaylistIdTrackId(PlaylistId, TrackId).FirstOrDefault());
        }

        // GET: PlaylistTrack/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaylistTrack/Create
        [HttpPost]
        public ActionResult Create(PlaylistTrack playlistTrack)
        {
            try
            {
                _dbRepository.Insert(playlistTrack);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(playlistTrack);
            }
        }

        // GET: PlaylistTrack/Edit/5
        public ActionResult Edit(Int32 PlaylistId, Int32 TrackId)
        {
            return View(_dbRepository.GetDataByPlaylistIdTrackId(PlaylistId, TrackId).FirstOrDefault());
        }

        // POST: PlaylistTrack/Edit/5
        [HttpPost]
        public ActionResult Edit(PlaylistTrack playlistTrack)
        {
            try
            {
                _dbRepository.Update(playlistTrack);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(playlistTrack);
            }
        }
   
       
    }
}
