//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.UI.Web.Controllers
{
    public class PlaylistController : Controller
    {
        private readonly IPlaylistRepository _dbPlaylistRepository;
        

        public PlaylistController(IPlaylistRepository dbPlaylistRepository)
        {
            _dbPlaylistRepository = dbPlaylistRepository;
            
        }
        
        // GET: Playlist
        public ActionResult Index()
        {
            return View();
        }

        // GET: Playlist/Details/5
        [Route("Playlist/Details/{playlistId}", Name = "GetPlaylistDetails")]
        public ActionResult Details(Int32 playlistId)
        {
            return View(_dbPlaylistRepository.GetDataByPlaylistId(playlistId).FirstOrDefault());
        }

        // GET: Playlist/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Playlist/Create
        [HttpPost]
        public ActionResult Create(Playlist playlist)
        {
            try
            {
                _dbPlaylistRepository.Insert(playlist);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(playlist);
            }
        }

        // GET: Playlist/Edit/5
        [Route("Playlist/Edit/{playlistId}", Name = "GetPlaylistEdit")]
        public ActionResult Edit(Int32 playlistId)
        {
        	var playlist = _dbPlaylistRepository.GetDataByPlaylistId(playlistId).FirstOrDefault();    
            
            return View(playlist);
        }

        // POST: Playlist/Edit/5
        [Route("Playlist/Edit/{playlistId}", Name = "PostPlaylistEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 playlistId, Playlist playlist)
        {
            try
            {
                _dbPlaylistRepository.Update(playlist);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(playlist);
            }
        }
   }
}
