//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using Chinook.Data.Repository;
using Chinook.Domain.Entities;

namespace Chinook.Web.UI.Controllers
{
    public class TrackController : Controller
    {
        private readonly ITrackRepository _dbTrackRepository;
        private readonly IAlbumRepository _dbAlbumRepository;
        private readonly IMediaTypeRepository _dbMediaTypeRepository;
        private readonly IGenreRepository _dbGenreRepository;
        

        public TrackController(ITrackRepository dbTrackRepository, IAlbumRepository dbAlbumRepository, IMediaTypeRepository dbMediaTypeRepository, IGenreRepository dbGenreRepository)
        {
            _dbTrackRepository = dbTrackRepository;
            _dbAlbumRepository = dbAlbumRepository; 
            _dbMediaTypeRepository = dbMediaTypeRepository; 
            _dbGenreRepository = dbGenreRepository; 
            
        }
        
        // GET: Track
        public ActionResult Index()
        {
            return View();
        }

        // GET: Track/Details/5
        [Route("Track/Details/{trackId}", Name = "GetTrackDetails")]
        public ActionResult Details(Int32 trackId)
        {
            return View(_dbTrackRepository.GetDataByTrackId(trackId).FirstOrDefault());
        }

        // GET: Track/Create
        public ActionResult Create()
        {
            ViewBag.Albums = new SelectList(_dbAlbumRepository.GetData(), "AlbumId", "Title");
            ViewBag.MediaTypes = new SelectList(_dbMediaTypeRepository.GetData(), "MediaTypeId", "Name");
            ViewBag.Genres = new SelectList(_dbGenreRepository.GetData(), "GenreId", "Name");
            
            return View();
        }

        // POST: Track/Create
        [HttpPost]
        public ActionResult Create(Track track)
        {
            try
            {
                _dbTrackRepository.Insert(track);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(track);
            }
        }

        // GET: Track/Edit/5
        [Route("Track/Edit/{trackId}", Name = "GetTrackEdit")]
        public ActionResult Edit(Int32 trackId)
        {
        	var track = _dbTrackRepository.GetDataByTrackId(trackId).FirstOrDefault();    
            if (track != null) ViewBag.Albums = new SelectList(_dbAlbumRepository.GetData(), "AlbumId", "Title", track.AlbumId);
            if (track != null) ViewBag.MediaTypes = new SelectList(_dbMediaTypeRepository.GetData(), "MediaTypeId", "Name", track.MediaTypeId);
            if (track != null) ViewBag.Genres = new SelectList(_dbGenreRepository.GetData(), "GenreId", "Name", track.GenreId);
            
            return View(track);
        }

        // POST: Track/Edit/5
        [Route("Track/Edit/{trackId}", Name = "PostTrackEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 trackId, Track track)
        {
            try
            {
                _dbTrackRepository.Update(track);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(track);
            }
        }
   }
}
