//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var controllerId = 'mediaTypeIndexCtrl';
    angular.module('app').controller(controllerId, ['common', 'mediaTypeDataService', mediaTypeList]);

    function mediaTypeList(common, mediaTypeDataService) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);

        var vm = this;
        vm.news = {
            title: 'MediaType List',
            description: 'MediaType List'
        };
       
        vm.pagableResults = [];
        vm.title = 'MediaTypeList';
        vm.sortExpression = 'MediaTypeId';
        vm.currentPage = 1;
        vm.pageSize = 10;
        vm.deleteMediaType = deleteMediaType;

        activate();

        vm.pageChanged = function () {
            return getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize);
        };

        function activate() {
            var promises = [getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize)];
            common.activateController(promises, controllerId)
                .then(function () { log('Activated MediaType List View'); });
        }
        
        function getDataPageable(sortExpression, page, pageSize) {
            return mediaTypeDataService.getDataPageable(sortExpression, page, pageSize).then(function (results) {
                return  vm.pagableResults = results.data;
              });
        }

        function deleteMediaType(mediaTypeId) {
            alert("test worked");
          //  return mediaTypeDataService.deleteMediaType(mediaTypeId);
        };
    }
})();

