//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'albumDataService';
    angular.module('app').service(serviceId, ['$http', albumDataService]);

    function albumDataService($http) {
        var urlBase = '/api/albums';

        this.getData = function () {
            return $http.get(urlBase + '/all');
        };

        this.updateAlbum = function (album) {
            return $http.put(urlBase, album);
        };

        this.insertAlbum = function (album) {
            return $http.post(urlBase, album);
        };

        this.deleteAlbum = function (albumId) {
            return $http.Delete(urlBase, albumId);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) {
            return $http({
                url: urlBase,
                method: 'GET',
                params: {
                    sortExpression: sortExpression || '',
                    page: page || '',
                    pageSize: pageSize || ''
                }
            });
        };

        this.getDataByAlbumId = function (albumId) {
            return $http.get(urlBase + '/' + albumId);
        };

        this.getDataByArtistId = function (artistId) {
            return $http.get('/api/artists/' + artistId + '/albums/all');
        };

        this.getDataByArtistIdPageable = function (artistId, sortExpression, page, pageSize) {
            return $http({
                url: '/api/artists/' + artistId + '/albums',
                method: 'GET',
                params: {
                    artistId: artistId || '',
                    sortExpression: sortExpression || '',
                    page: page || '',
                    pageSize: pageSize || ''
                }
            });
        };


    }
})();

