//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'mediaTypeDataService';
    angular.module('app').service(serviceId, ['$http', mediaTypeDataService]);

    function mediaTypeDataService($http) {
        var urlBase = '/api/mediaTypes';

        this.getData = function () {
            return $http.get(urlBase + '/all');
        };

        this.updateMediaType = function (mediaType) {
            return $http.put(urlBase, mediaType);
        };

        this.insertMediaType = function (mediaType) {
            return $http.post(urlBase, mediaType);
        };

        this.deleteMediaType = function (mediaTypeId) {
            return $http.Delete(urlBase, mediaTypeId);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) {
            return $http({
                url: urlBase,
                method: 'GET',
                params: {
                    sortExpression: sortExpression || '',
                    page: page || '',
                    pageSize: pageSize || ''
                }
            });
        };

        this.getDataByMediaTypeId = function (mediaTypeId) {
            return $http.get(urlBase + '/' + mediaTypeId);
        };


    }
})();
