//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var controllerId = 'invoiceIndexCtrl';
    angular.module('app').controller(controllerId, ['common', 'invoiceDataService', invoiceList]);

    function invoiceList(common, invoiceDataService) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);

        var vm = this;
        vm.news = {
            title: 'Invoice List',
            description: 'Invoice List'
        };
       
        vm.pagableResults = [];
        vm.title = 'InvoiceList';
        vm.sortExpression = 'InvoiceId';
        vm.currentPage = 1;
        vm.pageSize = 10;
        vm.deleteInvoice = deleteInvoice;

        activate();

        vm.pageChanged = function () {
            return getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize);
        };

        function activate() {
            var promises = [getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize)];
            common.activateController(promises, controllerId)
                .then(function () { log('Activated Invoice List View'); });
        }
        
        function getDataPageable(sortExpression, page, pageSize) {
            return invoiceDataService.getDataPageable(sortExpression, page, pageSize).then(function (results) {
                return  vm.pagableResults = results.data;
              });
        }

        function deleteInvoice(invoiceId) {
            alert("test worked");
          //  return invoiceDataService.deleteInvoice(invoiceId);
        };
    }
})();

