'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.ObjectModel
Imports System.Xml.Serialization

Namespace Chinook.Domain.Entities
  <Serializable()>  _
  Partial Public Class AlbumList
     Inherits Collection(Of Album)
                
          Public Function First() As Album
          If  MyBase.Count > 0 Then
              Return MyBase.Item(0)
          Else
              Return Nothing
          End If
      End Function
  End Class

<Serializable()> _
Partial Public Class Album
     Private _albumId as Int32
     Private _title as String
     Private _artistId as Int32
    Private _Tracks as TrackList
    Private _Artist as Artist  

  Public Sub New()
    MyBase.New
    
 End Sub

  Public Sub New(ByVal albumId as Int32, ByVal title as String, ByVal artistId as Int32)
      MyBase.New()
      
        _albumId = albumId
        _title = title
        _artistId = artistId
  End Sub


    ''' <summary>
    ''' Public Property AlbumId
    ''' </summary>
    ''' <returns>AlbumId as Int32</returns>
    ''' <remarks></remarks>
    Public Property AlbumId() as Int32
        Get
            Return Me._albumId
        End Get
        Set(ByVal value as Int32)
             Me._albumId = value
        End Set
    End Property


    ''' <summary>
    ''' Public Property Title
    ''' </summary>
    ''' <returns>Title as String</returns>
    ''' <remarks></remarks>
    Public Property Title() as String
        Get
            Return Me._title
        End Get
        Set(ByVal value as String)
             Me._title = value
        End Set
    End Property


    ''' <summary>
    ''' Public Property ArtistId
    ''' </summary>
    ''' <returns>ArtistId as Int32</returns>
    ''' <remarks></remarks>
    Public Property ArtistId() as Int32
        Get
            Return Me._artistId
        End Get
        Set(ByVal value as Int32)
             Me._artistId = value
        End Set
    End Property


  Public Overridable Property Tracks() as TrackList
      Get
          Return  _Tracks
      End Get
      Set(ByVal value As TrackList)
          _Tracks = value
      End Set
  End Property   
  

  Public Overridable Property Artist() as Artist
      Get
          Return  _Artist
      End Get
      Set(ByVal value As Artist)
          _Artist = value
      End Set
  End Property   
  

    End Class
End Namespace
 