//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace Chinook.Domain.Entities
{
    [Serializable()]
    public partial class PlaylistTrackList :  Collection<PlaylistTrack>
    {
        public PlaylistTrack First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract()]
    public partial class PlaylistTrack{
      
        private Int32 _playlistId;
        private Int32 _trackId; 
        private Playlist _playlist; 
        private Track _track;  

      public PlaylistTrack() : base()
      {
      }

      public PlaylistTrack(Int32 playlistId, Int32 trackId) : base()
      {
          
           _playlistId = playlistId;
           _trackId = trackId;
      }
  
    
        /// <summary>
        /// Public Property PlaylistId
        /// </summary>
        /// <returns>PlaylistId as Int32</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int32 PlaylistId
        {
            get{return this._playlistId;}
            set{this._playlistId = value;}
        }

        /// <summary>
        /// Public Property TrackId
        /// </summary>
        /// <returns>TrackId as Int32</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int32 TrackId
        {
            get{return this._trackId;}
            set{this._trackId = value;}
        }

        [DataMember()]
        public virtual Playlist Playlist 
        {
          get { return  _playlist;}
          set { _playlist = value;}
        }
  
      
        [DataMember()]
        public virtual Track Track 
        {
          get { return  _track;}
          set { _track = value;}
        }
  
      
    }
 }     
